---
title: "Week 3"
output: html_notebook
---


## Subsetting and Sorting

```{r}
set.seed(13435)
X <- data.frame(
  "var1" = sample(1:5),
  "var2" = sample(6:10),
  "var3" = sample(11:15)
)
X <- X[sample(1:5),]
X$var2[c(1,3)] <- NA
X
```


```{r}
X <- data.frame(
  var1 = c(2, 1, 3, 5, 4),
  var2 = c(NA, 10, NA, 6, 9),
  var3 = c(15, 11, 12, 14, 13)
)
X
```


```{r}
X[,1]
```


```{r}
X[,"var1"]
```


```{r}
X[1:2, "var2"]
```


```{r}
X[(X$var1 <= 3 & X$var3 > 11),]
```

```{r}
X[(X$var1 <= 3 | X$var3 > 15),]
```


```{r}
X[which(X$var2 > 8),]
```

```{r}
sort(X$var1)
```


```{r}
sort(X$var1, decreasing = TRUE)
```


```{r}
sort(X$var2, na.last = TRUE)
```



```{r}
X[order(X$var1),]
```


```{r}
X[order(X$var1, X$var3),]
```


```{r}
library(dplyr)
arrange(X, var1)
```

```{r}
arrange(X, desc(var1))
```

```{r}
X$var4 <- rnorm(5)
X
```

```{r}
Y <- cbind(X, rnorm(5))
Y
```




## Summarizaing data

```{r}
if(!file.exists("./data")) {
  dir.create("./data")
}
fileUrl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl, destfile = "./data/restaurants.csv", method = "curl")
restData <- read.csv("./data/restaurants.csv")
```


```{r}
head(restData, n = 3)
```


```{r}
tail(restData, n = 3)
```


```{r}
summary(restData)
```


```{r}
str(restData)
```


```{r}
quantile(restData$councilDistrict, na.rm = TRUE)
```


```{r}
quantile(restData$councilDistrict, probs = c(0.5, 0.75, 0.9))
```


```{r}
table(restData$zipCode, useNA = "ifany")
```


```{r}
table(restData$councilDistrict, restData$zipCode)
```


```{r}
sum(is.na(restData$councilDistrict))
```


```{r}
any(is.na(restData$councilDistrict))
```


```{r}
all(restData$zipCode > 0)
```

```{r}
colSums(is.na(restData))
```


```{r}
all(colSums(is.na(restData)) == 0)
```


```{r}
table(restData$zipCode %in% c("21212"))
```

```{r}
table(restData$zipCode %in% c("21212", "21213"))
```

```{r}
resData[restData$zipCode %in% c("21212", "21213"),]
```


```{r}
data(UCBAdmissions)
DF <- as.data.frame(UCBAdmissions)
summary(DF)
```


```{r}
xt <- xtabs(Freq ~ Gender + Admit, data = DF)
xt
```


```{r}
warpbreaks$replicate <- rep(1:9, len = 54)
warpbreaks
xt <- xtabs(breaks ~., data = warpbreaks)
xt
```

```{r}
warpbreaks
```


```{r}
ftable(xt)
```



```{r}
fakeData <- rnorm(1e5)
object.size(fakeData)
```

```{r}
print(object.size(fakeData), units = "Mb")
```



## Creating New Variables


```{r}

```

