---
title: "Week 3"
output: html_notebook
---


# Lesson 1: Hierarchical Clustering

```{r}
set.seed(1234)
par(pty= "s")
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
```


```{r}
dataFrame <- data.frame(x = x, y = y)
distxy <- dist(dataFrame)
hClustering <- hclust(distxy)
plot(hClustering)
```


```{r}
myplclust <- function(hclust, 
                      lab = hclust$labels, 
                      lab.col = rep(1, length(hclust$labels)),
                      hang = 0.1, ...) 
  {
    y <- rep(hclust$height, 2)
    x <- as.numeric(hclust$merge)
    y <- y[which(x < 0)]
    x <- x[which(x < 0)]
    x <- abs(x)
    y <- y[order(x)]
    x <- x[order(x)]
    plot(hclust, labels = FALSE, hang = hang, ...)
    text(x = x, y = y[hclust$order] - (max(hclust$height) * hang),
         labels = lab[hclust$order], col = lab.col[hclust$order],
         srt = 90, adj = c(1, 0.5), xpd = NA, ...)
  }
```


```{r}
myplclust(hClustering, lab = rep(1:3, each = 4), lab.col = rep(1:3, each = 4))
```


```{r}
dataFrame <- data.frame(x = x, y = y)
set.seed(143)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
heatmap(dataMatrix)
```


```{r}
set.seed(1234)
par(mar = c(2, 2, 2, 2), pty = "s")
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
```


```{r}
# kmeans()
dataFrame <- data.frame(x, y)
kmeansObj <- kmeans(dataFrame, centers = 3)
names(kmeansObj)
kmeansObj$cluster
```


```{r}
par(pty = "s")
plot(x, y, col = kmeansObj$cluster, pch = 19, cex = 2)
points(kmeansObj$centers, col = 1:3, pch = 3, cex = 3, lwd = 3)
```


```{r}
# Heatmaps
set.seed(1234)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
kmeansObj2 <- kmeans(dataMatrix, centers = 3)
par(mfrow = c(1, 2), mar = c(2, 4, 0.1, 0.1))
image(t(dataMatrix)[, nrow(dataMatrix):1], yaxt = "n")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yaxt = "n")
# K-means is not deterministic: different # of cluesters/iterations
```


# Lesson 2: K-Means Clustering & Dimension Reduction

```{r}
## Dimension Reduction: PCA & SVD
# Matrix data
set.seed(12345)
par(mar = rep(0.2, 4), pty = "s")
dataMatrix <- matrix(rnorm(400), nrow = 40)
image(1:10, 1:40, t(dataMatrix)[, nrow(dataMatrix):1])
```


```{r}
par(mar = rep(0.2, 4))
heatmap(dataMatrix)
```


```{r}
# Add a pattern
set.seed(678910)
for (i in 1:40) {
    # flip a coin
    coinFlip <- rbinom(1, size = 1, prob = 0.5)
    if(coinFlip) {
        dataMatrix[i, ] <- dataMatrix[i, ] + rep(c(0, 3), each = 5)
    }
}
par(mar = rep(0.2, 4))
image(1:10, 1:40, t(dataMatrix)[, nrow(dataMatrix):1])
heatmap(dataMatrix)
```


```{r}
# Patterns in rows and columns
hh <- hclust(dist(dataMatrix))
dataMatrixOrdered <- dataMatrix[hh$order, ]
par(mfrow = c(1, 3))
image(t(dataMatrixOrdered)[, nrow(dataMatrixOrdered):1])
plot(rowMeans(dataMatrixOrdered), 40:1, , xlab = "Row Mean", ylab = "Row", pch = 19)
plot(colMeans(dataMatrixOrdered), xlab = "Column", ylab = "Column Mean", pch = 19)
```


```{r}
## Components of the SVD
svd1 <- svd(scale(dataMatrixOrdered))
par(mfrow = c(1, 3))
image(t(dataMatrixOrdered)[, nrow(dataMatrixOrdered):1])
plot(svd1$u[, 1], 40:1, , xlab = "Row", ylab = "First left singular vector", 
     pch = 19)
plot(svd1$v[, 1], xlab = "Column", ylab = "First right singular vector", pch = 19)
```


```{r}
# - variance explained
par(mfrow = c(1, 2))
plot(svd1$d, xlab = "Column", ylab = "Singular value", pch = 19)
plot(svd1$d^2 / sum(svd1$d^2), xlab = "Column", ylab = "Prop. of variance explained", 
     pch = 19)
```


```{r}
# relationship to principal components
svd1 <- svd(scale(dataMatrixOrdered))
pca1 <- prcomp(dataMatrixOrdered, scale = TRUE)
par(pty = "s")
plot(pca1$rotation[, 1], svd1$v[, 1], pch = 19, xlab = "Principal Component 1", 
     ylab = "Right Singular Vector 1")
abline(c(0, 1))
```


```{r}
# Components of the svd - variance explained
constantMatrix <- dataMatrixOrdered*0
for(i in 1:dim(dataMatrixOrdered)[1]){constantMatrix[i,] <- rep(c(0,1),each=5)}
svd1 <- svd(constantMatrix)
par(mfrow = c(1,3))
image(t(constantMatrix)[, nrow(constantMatrix):1])
plot(svd1$d, xlab = "Column", ylab="Singular value", pch = 19)
plot(svd1$d^2 / sum(svd1$d^2), xlab = "Column", 
     ylab = "Prop. of variance explained", pch = 19)
```


```{r}
# Add a second pattern
set.seed(678910)
for (i in 1:40) {
    # flip a coin
    coinFlip1 <- rbinom(1, size = 1, prob = 0.5)
    coinFlip2 <- rbinom(1, size = 1, prob = 0.5)
    # if coin is heads add a common pattern to that row
    if (coinFlip1) {
        dataMatrix[i, ] <- dataMatrix[i, ] + rep(c(0, 5), each = 5)
    }
    if (coinFlip2) {
        dataMatrix[i, ] <- dataMatrix[i, ] + rep(c(0, 5), 5)
    }
}
hh <- hclust(dist(dataMatrix))
dataMatrixOrdered <- dataMatrix[hh$order, ]
```


```{r}
# SVD - true patterns
svd2 <- svd(scale(dataMatrixOrdered))
par(mfrow = c(1, 3))
image(t(dataMatrixOrdered)[, nrow(dataMatrixOrdered):1])
plot(rep(c(0, 1), each = 5), pch = 19, xlab = "Column", ylab = "Pattern 1")
plot(rep(c(0, 1), 5), pch = 19, xlab = "Column", ylab = "Pattern 2")
```


```{r}
# v and patterns of variance in rows
svd2 <- svd(scale(dataMatrixOrdered))
par(mfrow = c(1, 3))
image(t(dataMatrixOrdered)[, nrow(dataMatrixOrdered):1])
plot(svd2$v[, 1], pch = 19, xlab = "Column", ylab = "First right singular vector")
plot(svd2$v[, 2], pch = 19, xlab = "Column", ylab = "Second right singular vector")
```


```{r}
# d and variance explained
svd1 <- svd(scale(dataMatrixOrdered))
par(mfrow = c(1, 2))
plot(svd1$d, xlab = "Column", ylab = "Singular value", pch = 19)
plot(svd1$d^2/sum(svd1$d^2), xlab = "Column", ylab = "Percent of variance explained", 
     pch = 19)
```


```{r}
## Missing values
dataMatrix2 <- dataMatrixOrdered
# Randomly insert some missing data
dataMatrix2[sample(1:100, size = 40, replace = FALSE)] <- NA
#svd1 <- svd(scale(dataMatrix2))  ## Doesn't work!
```


```{r}
# source("http://bioconductor.org/biocLite.R")
# biocLite("impute")
# library(impute)  ## Available from http://bioconductor.org
# dataMatrix2 <- dataMatrixOrdered
# dataMatrix2[sample(1:100, size = 40, replace = FALSE)] <- NA
# dataMatrix2 <- impute.knn(dataMatrix2)$data
# svd1 <- svd(scale(dataMatrixOrdered))
# svd2 <- svd(scale(dataMatrix2))
# par(mfrow = c(1,2))
# plot(svd1$v[,1], pch = 19)
# plot(svd2$v[,1], pch = 19)
```


```{r}
# Face example
load("face.rda")
par(pty = "s")
image(t(faceData)[, nrow(faceData):1], col = heat.colors(128))
```


```{r}
# Variance explained
svd1 <- svd(scale(faceData))
plot(svd1$d^2 / sum(svd1$d^2), pch = 19, 
     xlab = "Singular vector", ylab = "Variance explained")
```


```{r}
# Create approximatation
vd1 <- svd(scale(faceData))
## Note that %*% is matrix multiplication

# Here svd1$d[1] is a constant
approx1 <- svd1$u[, 1] %*% t(svd1$v[, 1]) * svd1$d[1]

# In these examples we need to make the diagonal matrix out of d
approx5 <- svd1$u[, 1:5] %*% diag(svd1$d[1:5]) %*% t(svd1$v[, 1:5])
approx10 <- svd1$u[, 1:10] %*% diag(svd1$d[1:10]) %*% t(svd1$v[, 1:10])

# Plot approximations
col = heat.colors(128)
par(mfrow = c(1, 4), pty = "s")
image(t(approx1)[, nrow(approx1):1], main = "(a)", col = col)
image(t(approx5)[, nrow(approx5):1], main = "(b)", col = col)
image(t(approx10)[, nrow(approx10):1], main = "(c)", col = col)
image(t(faceData)[, nrow(faceData):1], main = "(d)", col = col)  ## Original data
```


# Lesson 3: Working with Color

```{r}
head(colors())
```


```{r}
pal <- colorRamp(c("red", "blue"))
pal(0)
pal(0.5)
str(pal(1))
```


```{r}
pal(seq(0, 1, len = 10))
```


```{r}
pal <- colorRampPalette(c("red", "yellow"))
pal(2)
pal(10)
```


```{r}
library(RColorBrewer)
cols <- brewer.pal(3, "BuGn")
cols
```


```{r}
pal <- colorRampPalette(cols)
par(pty = "s")
image(volcano, col = pal(20))
image(volcano, col = cols)
```


```{r}
par(pty = "s")
image(volcano, col = heat.colors(128))
```


```{r}
x <- rnorm(10000)
y <- rnorm(10000)
par(pty = "s")
smoothScatter(x, y)
```


```{r}
x <- rnorm(1000)
y <- rnorm(1000)
par(pty = "s")
plot(x, y, col = rgb(0, 0, 0, 0.3))
```


