---
title: "Week 3"
output: html_notebook
---


## Subsetting and Sorting

```{r}
set.seed(13435)
X <- data.frame(
  "var1" = sample(1:5),
  "var2" = sample(6:10),
  "var3" = sample(11:15)
)
X <- X[sample(1:5),]
X$var2[c(1,3)] <- NA
X
```


```{r}
X <- data.frame(
  var1 = c(2, 1, 3, 5, 4),
  var2 = c(NA, 10, NA, 6, 9),
  var3 = c(15, 11, 12, 14, 13)
)
X
```


```{r}
X[,1]
```


```{r}
X[,"var1"]
```


```{r}
X[1:2, "var2"]
```


```{r}
X[(X$var1 <= 3 & X$var3 > 11),]
```

```{r}
X[(X$var1 <= 3 | X$var3 > 15),]
```


```{r}
X[which(X$var2 > 8),]
```

```{r}
sort(X$var1)
```


```{r}
sort(X$var1, decreasing = TRUE)
```


```{r}
sort(X$var2, na.last = TRUE)
```



```{r}
X[order(X$var1),]
```


```{r}
X[order(X$var1, X$var3),]
```


```{r}
library(dplyr)
arrange(X, var1)
```

```{r}
arrange(X, desc(var1))
```

```{r}
X$var4 <- rnorm(5)
X
```

```{r}
Y <- cbind(X, rnorm(5))
Y
```




## Summarizaing data

```{r}
if(!file.exists("./data")) {
  dir.create("./data")
}
fileUrl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl, destfile = "./data/restaurants.csv", method = "curl")
restData <- read.csv("./data/restaurants.csv")
```


```{r}
head(restData, n = 3)
```


```{r}
tail(restData, n = 3)
```


```{r}
summary(restData)
```


```{r}
str(restData)
```


```{r}
quantile(restData$councilDistrict, na.rm = TRUE)
```


```{r}
quantile(restData$councilDistrict, probs = c(0.5, 0.75, 0.9))
```


```{r}
table(restData$zipCode, useNA = "ifany")
```


```{r}
table(restData$councilDistrict, restData$zipCode)
```


```{r}
sum(is.na(restData$councilDistrict))
```


```{r}
any(is.na(restData$councilDistrict))
```


```{r}
all(restData$zipCode > 0)
```

```{r}
colSums(is.na(restData))
```


```{r}
all(colSums(is.na(restData)) == 0)
```


```{r}
table(restData$zipCode %in% c("21212"))
```

```{r}
table(restData$zipCode %in% c("21212", "21213"))
```

```{r}
resData[restData$zipCode %in% c("21212", "21213"),]
```


```{r}
data(UCBAdmissions)
DF <- as.data.frame(UCBAdmissions)
summary(DF)
```


```{r}
xt <- xtabs(Freq ~ Gender + Admit, data = DF)
xt
```


```{r}
warpbreaks$replicate <- rep(1:9, len = 54)
warpbreaks
xt <- xtabs(breaks ~., data = warpbreaks)
xt
```

```{r}
warpbreaks
```


```{r}
ftable(xt)
```



```{r}
fakeData <- rnorm(1e5)
object.size(fakeData)
```

```{r}
print(object.size(fakeData), units = "Mb")
```



## Creating New Variables

```{r}
restData <- read.csv("./data/restaurants.csv")
```

```{r}
s1 <- seq(1, 10, by = 2)
s1
```


```{r}
s2 <- seq(1, 10, length = 3)
s2
```


```{r}
x <- c(1, 3, 8, 25, 100)
seq(along = x)
```


```{r}
restData$nearMe <- restData$neighborhood %in% c("Roland Park", "Homeland")
table(restData$nearMe)
```


```{r}
restData$zipWrong <- ifelse(restData$zipCode < 0, TRUE, FALSE)
table(restData$zipWrong, restData$zipCode < 0)
```


```{r}
restData$zipGroups <- cut(restData$zipCode, breaks = quantile(restData$zipCode))
table(restData$zipGroups)
```


```{r}
table(restData$zipGroups, restData$zipCode)
```

```{r}
#install.packages("Hmisc")
library(Hmisc)
restData$zipGroups = cut2(restData$zipCode, g = 4)
table(restData$zipGroups)
```


```{r}
restData$zcf <- factor(restData$zipCode)
restData$zcf[1:10]
```

```{r}
class(restData$zcf)
```

```{r}
yesno <- sample(c("yes", "no"), size = 10, replace = TRUE)
yesnofac <- factor(yesno, levels = c("yes", "no"))
yesnofac
```

```{r}
relevel(yesnofac, ref = "yes")
```

```{r}
as.numeric(yesnofac)
```


```{r}
library(dplyr)
restData2 <- mutate(restData, zipGroups <- cut2(zipCode, g = 4))
table(restData2$zipGroups)
```



## Reshaping data


```{r}
library(reshape2)
head(mtcars)
```


```{r}
mtcars$carname <- rownames(mtcars)
carMelt <- melt(mtcars, id = c("carname", "gear", "cyl"), measure.vars = c("mpg", "hp"))
head(carMelt, n = 3)
```

```{r}
mtcars %>% 
  pivot_longer(c(mpg, hp), names_to = "variable", values_to = "value") %>% 
  select(carname, gear, cyl, variable, value) %>% 
  arrange(desc(variable))
```


```{r}
cylData <- dcast(carMelt, cyl ~ variable, mean)
cylData
```

```{r}
InsectSprays
```

```{r}
tapply(InsectSprays$count, InsectSprays$spray, sum)
```


```{r}
spIns <- split(InsectSprays$count, InsectSprays$spray)
spIns
```

```{r}
sprCount <- lapply(spIns, sum)
sprCount
```

```{r}
unlist(sprCount)
```

```{r}
sapply(spIns, sum)
```


```{r}
InsectSprays %>% 
  group_by(spray) %>% 
  summarize(sum = sum(count))
```


```{r}
InsectSprays %>% 
  group_by(spray) %>% 
  summarize(
    sum = sum(count)
  )
```


## Managing Data Frames with dplyr - Introduction



## Managing Data Frames with dplyr - Basic Tools


## Merging data




## Week 3 Quiz

### 1

```{r}
library(tidyverse)
df <- read_csv("../input/getdata_data_ss06hid.csv")
str(df)
```

```{r}
df
```

```{r}
table(df$AGS)
```


```{r}
agricultureLogical <- df$ACR == 3 & df$AGS == 6
which(agricultureLogical)
```


### 2

```{r}
library(jpeg)
j1 <- readJPEG("../input/getdata_jeff.jpg", native = TRUE)
j1
```


```{r}
quantile(j1, probs = c(.3, .8))
```


### 3

```{r}
raw <- read_csv("../input/getdata_data_GDP.csv")
raw
```

```{r}
df <- raw[-(1:4), c(1, 2, 4, 5)]
names(df) <- c("CountryCode", "ranking", "country", "gdp")
df <- df[complete.cases(df),]
```


```{r}
raw2 <- read_csv("../input/getdata_data_EDSTATS_Country.csv")
raw2
```

```{r}
length(intersect(df$CountryCode, raw2$CountryCode))
```


```{r}
df %>% 
  mutate(rank = as.numeric(ranking)) %>% 
  arrange(desc(rank)) %>% slice(13)
```



```{r}
df2 <- df %>% 
  left_join(raw2, by = "CountryCode") %>% 
  mutate(
    ranking = as.numeric(ranking),
    gdp = parse_number(gdp)
  )
df2
```
```{r}
df2 %>% 
  filter(`Income Group` == "High income: OECD") %>% 
  summarize(mean(ranking))
```


```{r}
df2 %>% 
  filter(`Income Group` == "High income: nonOECD") %>% 
  summarize(mean(ranking))
```



```{r}
library(Hmisc)
df2 %>% 
  mutate(group = cut2(df2$ranking, g = 5)) %>% 
  relocate(group)
```

```{r}
group <- cut2(df2$ranking, g = 5)
```

```{r}
table(group, df2$`Income Group`)
```






